-- PostgreSQL: tabelas no schema privado grimorio.
CREATE TABLE users (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name TEXT NOT NULL CHECK(length(trim(name)) > 0),
 email TEXT NOT NULL UNIQUE CHECK(email = lower(email)),
 password_hash TEXT NOT NULL,
 created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);
CREATE TABLE sources (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name TEXT NOT NULL CHECK(length(trim(name)) > 0),
 kind TEXT NOT NULL CHECK(kind IN ('book','compendium','homebrew')),
 owner_user_id INTEGER REFERENCES users(id) ON DELETE RESTRICT,
 reference TEXT,
 CHECK(kind <> 'homebrew' OR owner_user_id IS NOT NULL)
);
CREATE TABLE schools (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name TEXT NOT NULL UNIQUE
);
CREATE TABLE classes (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name TEXT NOT NULL CHECK(length(trim(name)) > 0),
 search_name TEXT NOT NULL,
 source_id INTEGER NOT NULL REFERENCES sources(id) ON DELETE RESTRICT,
 UNIQUE(source_id, name)
);
CREATE TABLE spells (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name TEXT NOT NULL CHECK(length(trim(name)) > 0),
 search_name TEXT NOT NULL,
 level INTEGER NOT NULL CHECK(level BETWEEN 0 AND 9),
 school_id INTEGER NOT NULL REFERENCES schools(id) ON DELETE RESTRICT,
 source_id INTEGER NOT NULL REFERENCES sources(id) ON DELETE RESTRICT,
 components_text TEXT NOT NULL,
 casting_time_text TEXT NOT NULL,
 range_text TEXT NOT NULL,
 duration_text TEXT NOT NULL,
 description_text TEXT NOT NULL,
 image_path TEXT,
 source_page INTEGER CHECK(source_page IS NULL OR source_page > 0),
 source_school_text TEXT,
 original_entry_json TEXT CHECK(original_entry_json IS NULL OR original_entry_json::jsonb IS NOT NULL),
 created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
 updated_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
 UNIQUE(source_id,name)
);
-- Uma origem registra a inclusão de uma magia em uma classe.
-- A mesma magia pode ter vínculos de origens diferentes.
CREATE TABLE class_spells (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 class_id INTEGER NOT NULL REFERENCES classes(id) ON DELETE RESTRICT,
 spell_id INTEGER NOT NULL REFERENCES spells(id) ON DELETE RESTRICT,
 source_id INTEGER NOT NULL REFERENCES sources(id) ON DELETE RESTRICT,
 UNIQUE(class_id,spell_id,source_id)
);
CREATE TABLE characters (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 class_id INTEGER NOT NULL REFERENCES classes(id) ON DELETE RESTRICT,
 name TEXT NOT NULL CHECK(length(trim(name)) > 0),
 level INTEGER NOT NULL DEFAULT 1 CHECK(level BETWEEN 1 AND 20),
 created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
);
-- Referencia o vínculo escolhido: preserva a origem que autorizou a preparação.
CREATE TABLE prepared_spells (
 character_id INTEGER NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
 class_spell_id INTEGER NOT NULL REFERENCES class_spells(id) ON DELETE RESTRICT,
 spell_id INTEGER NOT NULL REFERENCES spells(id) ON DELETE RESTRICT,
 UNIQUE(character_id,spell_id),
 prepared_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
 PRIMARY KEY(character_id,class_spell_id)
);
CREATE INDEX idx_characters_user ON characters(user_id);
CREATE INDEX idx_characters_class ON characters(class_id);
CREATE INDEX idx_spells_search ON spells(search_name);
CREATE INDEX idx_spells_school ON spells(school_id);
CREATE INDEX idx_spells_source ON spells(source_id);
CREATE INDEX idx_classes_source ON classes(source_id);
CREATE INDEX idx_class_spells_spell ON class_spells(spell_id);
CREATE INDEX idx_class_spells_source ON class_spells(source_id);
CREATE INDEX idx_prepared_link ON prepared_spells(class_spell_id);
CREATE INDEX idx_sources_owner ON sources(owner_user_id);


CREATE TABLE sessions (
 token_hash TEXT PRIMARY KEY,
 user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 expires_at BIGINT NOT NULL,
 created_at BIGINT NOT NULL
);
CREATE INDEX idx_sessions_user ON sessions(user_id);
CREATE INDEX idx_sessions_expiration ON sessions(expires_at);

CREATE FUNCTION validate_prepared() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 PERFORM 1 FROM characters WHERE id=NEW.character_id FOR UPDATE;
 IF NOT EXISTS (
  SELECT 1 FROM characters c
  JOIN class_spells cs ON cs.id=NEW.class_spell_id AND cs.class_id=c.class_id
  JOIN spells s ON s.id=cs.spell_id
  JOIN classes cl ON cl.id=c.class_id
  JOIN sources ss ON ss.id=s.source_id
  JOIN sources ls ON ls.id=cs.source_id
  JOIN sources cls ON cls.id=cl.source_id
  WHERE c.id=NEW.character_id
   AND (ss.owner_user_id IS NULL OR ss.owner_user_id=c.user_id)
   AND (ls.owner_user_id IS NULL OR ls.owner_user_id=c.user_id)
   AND (cls.owner_user_id IS NULL OR cls.owner_user_id=c.user_id)
 ) THEN RAISE EXCEPTION 'Magia indisponível para este personagem'; END IF;
 SELECT spell_id INTO NEW.spell_id FROM class_spells WHERE id=NEW.class_spell_id;
 RETURN NEW;
END $$;
CREATE TRIGGER prepared_insert_validate BEFORE INSERT ON prepared_spells
 FOR EACH ROW EXECUTE FUNCTION validate_prepared();

CREATE FUNCTION protect_records() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_TABLE_NAME IN ('prepared_spells','class_spells') THEN
  RAISE EXCEPTION 'Vínculo imutável: remova e crie outro';
 ELSIF TG_TABLE_NAME='characters' THEN
  IF NEW.user_id IS DISTINCT FROM OLD.user_id THEN RAISE EXCEPTION 'O dono do personagem não pode ser alterado'; END IF;
  IF NEW.class_id IS DISTINCT FROM OLD.class_id AND EXISTS(SELECT 1 FROM prepared_spells WHERE character_id=OLD.id) THEN
   RAISE EXCEPTION 'Desprepare as magias antes de trocar de classe';
  END IF;
 ELSIF TG_TABLE_NAME='sources' THEN
  IF NEW.owner_user_id IS DISTINCT FROM OLD.owner_user_id OR NEW.kind IS DISTINCT FROM OLD.kind THEN
   RAISE EXCEPTION 'Crie uma nova origem para alterar autoria ou tipo';
  END IF;
 ELSIF TG_TABLE_NAME IN ('spells','classes') THEN
  IF NEW.source_id IS DISTINCT FROM OLD.source_id THEN RAISE EXCEPTION 'A origem é imutável'; END IF;
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER protect_prepared BEFORE UPDATE ON prepared_spells FOR EACH ROW EXECUTE FUNCTION protect_records();
CREATE TRIGGER protect_links BEFORE UPDATE ON class_spells FOR EACH ROW EXECUTE FUNCTION protect_records();
CREATE TRIGGER protect_characters BEFORE UPDATE ON characters FOR EACH ROW EXECUTE FUNCTION protect_records();
CREATE TRIGGER protect_sources BEFORE UPDATE ON sources FOR EACH ROW EXECUTE FUNCTION protect_records();
CREATE TRIGGER protect_spells BEFORE UPDATE ON spells FOR EACH ROW EXECUTE FUNCTION protect_records();
CREATE TRIGGER protect_classes BEFORE UPDATE ON classes FOR EACH ROW EXECUTE FUNCTION protect_records();
